/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export declare class Client {
  constructor(providerPath: string, options?: any | undefined | null)
  complete(prompt: any): Promise<any>
}
