/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export declare function loadPrompt(path: string): any
export declare function createPrompt(options: any): any
export declare function simplePrompt(options?: any | undefined | null): any
export declare class Client {
  constructor(provider: string, options?: any | undefined | null)
  complete(prompt: any): Promise<any>
  completeFile(path: string): Promise<any>
  completeText(message: string, options?: any | undefined | null): Promise<any>
}
