/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export type ClientAuditTarget = "stdout" | { file: string }

export interface ClientAuditOptions {
  target?: ClientAuditTarget
  redact?: string[]
}

export interface ClientWatchOptions {
  enable?: boolean
  paths?: string[]
  debounceMs?: number
}

export interface ClientOptions {
  model?: string
  providersDir?: string
  watch?: ClientWatchOptions | null
  audit?: ClientAuditOptions | null
}

export declare class Client {
  constructor(provider: string, options?: ClientOptions | null)
  complete(prompt: any): Promise<any>
}
